apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vehicle-telemetry-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/<your-github-username>/autogitops-platform.git
    targetRevision: main
    path: apps/vehicle-telemetry-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: vehicle-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
