apiVersion: v1
kind: Service
metadata:
  name: vehicle-telemetry-demo
  namespace: vehicle-demo
  labels:
    app: vehicle-telemetry-demo
spec:
  selector:
    app: vehicle-telemetry-demo
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
